### ISSUE TITLE
ruby-lsp at 100% CPU hanging in RubyLsp::Rails::RunnerClient#shutdown

### ISSUE THREAD

**Issue by tisba** [Shopify/ruby-lsp-rails#274]
I cannot reliably reproduce this, but it happens ever now and then. When I just saw it happening again, I attached `rbspy` to record what's going on, here is the flame graph:

![CleanShot 2024-02-27 at 16 02 45](https://github.com/Shopify/ruby-lsp-rails/assets/75156/9dd66d8b-7734-4549-8643-8e5e9009f3f2)

It looks like it is spinning at `Thread.pass while @wait_thread.alive?` here https://github.com/Shopify/ruby-lsp-rails/blob/main/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb#L67-L72.

In VSCode everything looks like it works normally. In the Ruby LSP output there is only one error, although I don't know if that's related to the issue:

```
/Users/sebastian/.gem/ruby/3.3.0/gems/ruby-lsp-0.14.3/lib/ruby_lsp/server.rb:112:in `push': queue closed (ClosedQueueError)
	from /Users/sebastian/.gem/ruby/3.3.0/gems/ruby-lsp-0.14.3/lib/ruby_lsp/server.rb:112:in `block in start'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/ruby-lsp-0.14.3/lib/ruby_lsp/server.rb:65:in `start'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/sorbet-runtime-0.5.11268/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/sorbet-runtime-0.5.11268/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/ruby-lsp-0.14.3/exe/ruby-lsp:104:in `<top (required)>'
	from /Users/sebastian/.gem/ruby/3.3.0/bin/ruby-lsp:25:in `load'
	from /Users/sebastian/.gem/ruby/3.3.0/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/sebastian/.gem/ruby/3.3.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /Users/sebastian/.gem/ruby/3.3.0/bin/bundle:25:in `load'
	from /Users/sebastian/.gem/ruby/3.3.0/bin/bundle:25:in `<main>'
```

When I kill the rougle ruby process, there is no output in the VSCode output tab and everything seems to work as normal. So maybe this is an orphaned process or something?

**Comment by andyw8** [comment]
@tisba This should in v0.3.2, could you give it a try?

**Comment by tisba** [comment]
@andyw8 see https://github.com/Shopify/ruby-lsp-rails/pull/276#issuecomment-1971897245
