### ISSUE TITLE
Investigate getpgid error.

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp-rails#291]
We are seeing occasionally on Core:

```
2024-03-14 14:51:11.636 [info] (shopify) Ruby LSP Rails failed to initialize server: /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/server.rb:84:in `getpgid': No such process (Errno::ESRCH)
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/server.rb:84:in `set_pgid'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/server.rb:39:in `boot'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/server.rb:14:in `boot'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/client/server.rb:10:in `call'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/client/command.rb:7:in `call'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/lib/spring/client.rb:30:in `run'
	from /home/spin/.bundle/shopify/ruby-3.3.0/gems/spring-4.1.3/bin/spring:49:in `<main>'

/home/spin/.bundle/shopify/ruby-3.3.0/bundler/gems/ruby-lsp-rails-641ab1e75661/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:75:in `rescue in initialize'
/home/spin/.bundle/shopify/ruby-3.3.0/bundler/gems/ruby-lsp-rails-641ab1e75661/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:37:in `initialize'
/home/spin/.bundle/shopify/ruby-3.3.0/gems/sorbet-runtime-0.5.11276/lib/types/private/methods/_methods.rb:279:in `bind_call'
/home/spin/.bundle/shopify/ruby-3.3.0/gems/sorbet-runtime-0.5.11276/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
/home/spin/.bundle/shopify/ruby-3.3.0/bundler/gems/ruby-lsp-rails-641ab1e75661/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `new'
/home/spin/.bundle/shopify/ruby-3.3.0/bundler/gems/ruby-lsp-rails-641ab1e75661/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `create_client'
/home/spin/.bundle/shopify/ruby-3.3.0/gems/sorbet-runtime-0.5.11276/lib/types/private/methods/_methods.rb:279:in `bind_call'
/home/spin/.bundle/shopify/ruby-3.3.0/gems/sorbet-runtime-0.5.11276/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
/home/spin/.bundle/shopify/ruby-3.3.0/bundler/gems/ruby-lsp-rails-641ab1e75661/lib/ruby_lsp/ruby_lsp_rails/addon.rb:29:in `block in activate'
```

**Comment by andyw8** [comment]
Can reproduce by running `spring stop` then restarting Ruby LSP.
