### ISSUE TITLE
Hover not working for AR model `Request textDocument/hover failed. `

### ISSUE THREAD

**Issue by brutuscat** [Shopify/ruby-lsp-rails#424]
```
2024-07-25 15:21:50.247 [info] (my_project) [Error - 15:21:50] Request textDocument/hover failed.
2024-07-25 15:21:50.248 [info] (my_project)   Message: /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.9/lib/ruby_indexer/lib/ruby_indexer/index.rb:245:in `resolve': undefined method `any?' [..]

      full_name = nesting.any? ? "#{nesting.join("::")}::#{name}" : name
                         ^^^^^
	from /Users/Anon/.gem/ruby/3.1.0/gems/ruby-lsp-rails-0.3.5/lib/ruby_lsp/ruby_lsp_rails/hover.rb:54:in `on_constant_read_node_enter'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/prism-0.30.0/lib/prism/dispatcher.rb:1532:in `block in visit_constant_read_node'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/prism-0.30.0/lib/prism/dispatcher.rb:1532:in `each'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/prism-0.30.0/lib/prism/dispatcher.rb:1532:in `visit_constant_read_node'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/prism-0.30.0/lib/prism/node.rb:5487:in `accept'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/prism-0.30.0/lib/prism/dispatcher.rb:66:in `dispatch_once'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.9/lib/ruby_lsp/requests/hover.rb:80:in `perform'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.9/lib/ruby_lsp/server.rb:481:in `text_document_hover'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.9/lib/ruby_lsp/server.rb:54:in `process_message'
	from /Users/Anon/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.9/lib/ruby_lsp/base_server.rb:128:in `block in new_worker'

  Code: -32603
```

**Comment by andyw8** [comment]
Hi, can you first try update ruby-lsp-rails to the latest release.

**Comment by brutuscat** [comment]
Hi, thx. I using the extension from VSCode and it does not show that it needs updating. And the ruby-lsp-rails seems bundled inside ruby-lsp right? How do I do that on VSCode?

**Comment by brutuscat** [comment]
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/dde0416c-557a-4428-9397-225e325510ae">

**Comment by andyw8** [comment]
You're on the latest VS Code extension version, but the `ruby-lsp-rails` addon is at ruby-lsp-rails addon gem is at v0.3.5, and the latest is v0.3.11.

Normally it gets auto-updated, but something in your bundle may be constraining it.

First you can try `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle update ruby-lsp ruby-lsp-rails`

If that doesn't work, then check if another gem may be constraining `rbs`, `sorbet-runtime` or `prism`.
