### ISSUE TITLE
Ruby LSP Rails failed to initialize server

### ISSUE THREAD

**Issue by reppiee** [Shopify/ruby-lsp-rails#452]
I've installed `ruby-lsp` and successfully using that using the Ruby LSP VSCode extension, however Ruby LSP Rails fails to initialize its server with the following error:

```
2024-09-16 11:47:06.554 [info] (core) Ruby LSP Rails failed to initialize server: 
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:94:in `rescue in initialize'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:43:in `initialize'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:279:in `bind_call'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `new'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `create_client'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:279:in `bind_call'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11422/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
/Users/steven/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/addon.rb:36:in `block in activate'
Server dependent features will not be available
```

Any ideas on why or what I could do to fix it?

**Comment by vinistock** [comment]
Thank you for the bug report! The backtrace seems to be incomplete for whatever reason, so it's hard to tell what's going on without the error message.

I do see that you're on v0.3.11 of `ruby-lsp-rails`, which is not the latest. Can you please try upgrading? Alternatively, do you see the error message printed anywhere?

**Comment by reppiee** [comment]
Sorry for not coming back to this - a colleague of mine went down the rabbithole and figured out that it was not starting properly due to customised rails bin stubs that we use.

Apologies and thanks for the help!
