### ISSUE TITLE
Ruby LSP Rails failed to initialize server

### ISSUE THREAD

**Issue by AlexVPopov** [Shopify/ruby-lsp-rails#514]
Hello,

Since today, I can't start the Ruby LSP server. Here's the output from the logs:

```
2024-11-06 17:20:09.075 [info] (platform) The Gemfile's dependencies are satisfied

2024-11-06 17:20:10.791 [info] (platform) Initializing Ruby LSP v0.21.3...
2024-11-06 17:20:10.796 [info] (platform) Auto detected formatter: rubocop
2024-11-06 17:20:10.796 [info] (platform) Auto detected linters: rubocop
2024-11-06 17:20:10.796 [info] (platform) Detected test library: rspec
2024-11-06 17:20:10.796 [info] (platform) Finished initializing Ruby LSP!
2024-11-06 17:20:10.955 [info] (platform) Activating Ruby LSP Rails add-on v0.3.23
2024-11-06 17:20:10.956 [info] (platform) Ruby LSP Rails booting server
2024-11-06 17:20:15.521 [info] (platform) [Error - 5:20:15 PM] Ruby LSP Rails failed to initialize server: /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:295:in `block in read_response': RubyLsp::Rails::RunnerClient::EmptyMessageError (RubyLsp::Rails::RunnerClient::EmptyMessageError)
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:292:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:292:in `read_response'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:90:in `initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `new'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `create_client'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11637/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `block (3 levels) in initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `block (2 levels) in initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/addon.rb:39:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.23/lib/ruby_lsp/ruby_lsp_rails/addon.rb:39:in `block in initialize'

Server dependent features will not be available

```

Below is the Ruby LSP debug information. Could you point me to how I can troubleshoot this problem? Thank you. :)

#### VS Code Version

1.95.1

#### Ruby LSP Extension Version

0.8.13

#### Ruby LSP Server Version

0.21.3

#### Ruby LSP Addons

- Ruby LSP Rails

#### Ruby Version

3.2.4

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- copilot (1.243.0)
- copilot-chat (0.22.1)
- elixir-ls (0.24.2)
- gitlens (15.6.3)
- go (0.42.1)
- makefile-tools (0.11.13)
- prettier-sql-vscode (1.6.0)
- rainbow-csv (3.12.0)
- ruby-extensions-pack (0.1.12)
- ruby-lsp (0.8.13)
- sorbet-vscode-extension (0.3.37)
- terraform (2.33.0)
- vscode-fileutils (3.10.3)
- vscode-graphql (0.12.1)
- vscode-json-validate (1.5.0)
- vscode-yaml (1.15.0)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "auto",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "/Users/alexanderpopov/.rbenv/shims/ruby",
  "indexing": {},
  "erbSupport": true,
  "useLauncher": false,
  "featureFlags": {}
}
```

</details>

**Comment by vinistock** [comment]
Thank you for the report! Can you please try the just released v0.3.24? I believe this is the same as #512.

**Comment by AlexVPopov** [comment]
Hey @vinistock, thank you for the quick reply! Unfortunately, this didn't solve the issue for me:

```shell
2024-11-07 13:28:21.469 [info] (platform) Initializing Ruby LSP v0.21.3...
2024-11-07 13:28:21.475 [info] (platform) Auto detected formatter: rubocop
2024-11-07 13:28:21.475 [info] (platform) Auto detected linters: rubocop
2024-11-07 13:28:21.475 [info] (platform) Detected test library: rspec
2024-11-07 13:28:21.475 [info] (platform) Finished initializing Ruby LSP!
2024-11-07 13:28:21.597 [info] (platform) Activating Ruby LSP Rails add-on v0.3.25
2024-11-07 13:28:21.599 [info] (platform) Ruby LSP Rails booting server
2024-11-07 13:28:26.341 [info] (platform) [Error - 1:28:26 PM] Ruby LSP Rails failed to initialize server: /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:296:in `block in read_response': RubyLsp::Rails::RunnerClient::EmptyMessageError (RubyLsp::Rails::RunnerClient::EmptyMessageError)
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:293:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:293:in `read_response'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:91:in `initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `new'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/runner_client.rb:16:in `create_client'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11641/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `block (3 levels) in initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/addon.rb:41:in `block (2 levels) in initialize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/addon.rb:39:in `synchronize'
	from /home/alexander/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.25/lib/ruby_lsp/ruby_lsp_rails/addon.rb:39:in `block in initialize'

Server dependent features will not be available
```

**Comment by erickguan** [comment]
I tried your patch. This problem persists. On my end, I have Mongoid 8.1.6.

**Comment by andyw8** [comment]
Do you see any errors if running this on the command line:

```
bundle exec rails runner PATH_TO_INSTALLATION/ruby-lsp-rails/lib/ruby_lsp/ruby_lsp_rails/server.rb start
```

(get the path using `bundle show ruby-lsp-rails`)

**Comment by erickguan** [comment]
This works well:

```
# logs for other initializers from the Rails app
Content-Length: 73

{"result":{"message":"ok","root":"/Users/erickg/repos/skvk/application"}}
```

**Comment by erickguan** [comment]
I bootstraped a 7.2.2 Rails with sqlite3. ruby-lsp-rails commit `b5235c3b937300cccaf734809d75f896355039e5`.

<details> 
<summary>Logs from VS Code Ruby LSP</summary>

```
2024-11-08 13:06:00.722 [info] (testapp) Found rbenv executable at /opt/homebrew/bin
2024-11-08 13:06:00.724 [info] (testapp) Running command: `/opt/homebrew/bin/rbenv exec ruby -W0 -rjson -e 'STDERR.print("RUBY_LSP_ACTIVATION_SEPARATOR" + { env: ENV.to_h, yjit: !!defined?(RubyVM::YJIT), version: RUBY_VERSION, gemPath: Gem.path }.to_json + "RUBY_LSP_ACTIVATION_SEPARATOR")'` in /Users/erickg/repos/skvk/testapp using shell: /opt/homebrew/bin/zsh
2024-11-08 13:06:00.772 [info] (testapp) [Error - 13:06:00] Server process exited with code 0.
2024-11-08 13:06:01.241 [info] (testapp) Ruby LSP> Skipping custom bundle setup since /Users/erickg/repos/skvk/testapp/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-11-08 13:06:01.283 [info] (testapp) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle _2.4.19_ check || bundle _2.4.19_ install) 1>&2

2024-11-08 13:06:01.455 [info] (testapp) The Gemfile's dependencies are satisfied

2024-11-08 13:06:02.452 [info] (testapp) Initializing Ruby LSP v0.21.3...
2024-11-08 13:06:02.457 [info] (testapp) Auto detected formatter: rubocop
2024-11-08 13:06:02.458 [info] (testapp) Auto detected linters: rubocop
2024-11-08 13:06:02.458 [info] (testapp) Detected test library: rails
2024-11-08 13:06:02.458 [info] (testapp) Finished initializing Ruby LSP!
2024-11-08 13:06:02.470 [info] (testapp) Activating Ruby LSP Rails add-on v0.3.25
2024-11-08 13:06:02.475 [info] (testapp) Ruby LSP Rails booting server
2024-11-08 13:06:03.580 [info] (testapp) Finished booting Ruby LSP Rails server
2024-11-08 13:06:40.219 [info] (testapp) Found rbenv executable at /opt/homebrew/bin
2024-11-08 13:06:40.219 [info] (testapp) Running command: `/opt/homebrew/bin/rbenv exec ruby -W0 -rjson -e 'STDERR.print("RUBY_LSP_ACTIVATION_SEPARATOR" + { env: ENV.to_h, yjit: !!defined?(RubyVM::YJIT), version: RUBY_VERSION, gemPath: Gem.path }.to_json + "RUBY_LSP_ACTIVATION_SEPARATOR")'` in /Users/erickg/repos/skvk/testapp using shell: /opt/homebrew/bin/zsh
2024-11-08 13:06:40.525 [info] (testapp) Shutting down Ruby LSP...
2024-11-08 13:06:40.526 [info] (testapp) Ruby LSP Rails shutting down server
2024-11-08 13:06:41.047 [info] (testapp) [Error - 13:06:41] Server process exited with code 0.
2024-11-08 13:06:41.250 [info] (testapp) Ruby LSP> Skipping custom bundle setup since /Users/erickg/repos/skvk/testapp/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-11-08 13:06:41.324 [info] (testapp) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle _2.4.19_ check || bundle _2.4.19_ install) 1>&2

2024-11-08 13:06:41.495 [info] (testapp) The Gemfile's dependencies are satisfied

2024-11-08 13:06:42.504 [info] (testapp) DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/bh/3stpknyx3vvc0kj_8k2l4htm0000gn/T/rdbg-501/rdbg-55875)

2024-11-08 13:06:42.509 [info] (testapp) Initializing Ruby LSP v0.21.3...
2024-11-08 13:06:42.512 [info] (testapp) Auto detected formatter: rubocop
2024-11-08 13:06:42.512 [info] (testapp) Auto detected linters: rubocop
2024-11-08 13:06:42.512 [info] (testapp) Detected test library: rails
2024-11-08 13:06:42.512 [info] (testapp) Finished initializing Ruby LSP!
2024-11-08 13:06:42.526 [info] (testapp) Activating Ruby LSP Rails add-on v0.3.25
2024-11-08 13:06:42.531 [info] (testapp) Ruby LSP Rails booting server
2024-11-08 13:06:43.490 [info] (testapp) Finished booting Ruby LSP Rails server
```
</details>


Everything looks fine. Then I did `bundle show ruby-lsp-rails`.

```
/Users/erickg/.local/share/mise/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/bundler/gems/ruby-lsp-rails-b5235c3b9373
```

Running `bundle exec rails runner lib/ruby_lsp/ruby_lsp_rails/server.rb start`

Same message:

```
Content-Length: 69

{"result":{"message":"ok","root":"/Users/erickg/repos/skvk/testapp"}}
```

Both repo has a direnv setup:
```
use rbenv

layout ruby

PATH_add bin
```

This is a bit bizzare. So I suspected my environment. I have both `mise` and `rbenv`. I use rbenv in Ruby LSP but not in an interactive shell. My direnv uses rbenv. So I disabled mise and applied the same check again. Now that Ruby LSP Rails runs well.

Now the problem should be which "bundle" Ruby LSP picks up. When `mise` is available, `mise` overwrites the 'direnv' bundle. I know this will cause undefined behavior. I will fix that integration.
The nuance to RubyLSP is though where RubyLSP loads the environment in this case.

**Comment by andyw8** [comment]
That app doesn't seem to start:

```
repro-ruby-lsp-rails main % bin/rails c
/Users/andyw8/.gem/ruby/3.3.4/gems/bundler-2.4.19/lib/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? sqlite3 is not part of the bundle. Add it to your Gemfile. (LoadError)
        from /Users/andyw8/.gem/ruby/3.3.4/gems/activerecord-7.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
```

**Comment by andyw8** [comment]
I can boot it if comment out the `active_record` Railtie and the mentions in `development.rb`. Continuing to investigate...

**Comment by erickguan** [comment]
Yep, it's `22`.

**Comment by AlexVPopov** [comment]
Meanwhile I don't have the problem, running on 0.3.26:

```shell
2024-11-09 07:17:59.034 [info] (platform) Initializing Ruby LSP v0.21.3...
2024-11-09 07:17:59.041 [info] (platform) Auto detected formatter: rubocop
2024-11-09 07:17:59.041 [info] (platform) Auto detected linters: rubocop
2024-11-09 07:17:59.041 [info] (platform) Detected test library: rspec
2024-11-09 07:17:59.041 [info] (platform) Finished initializing Ruby LSP!
2024-11-09 07:17:59.178 [info] (platform) Activating Ruby LSP Rails add-on v0.3.26
2024-11-09 07:17:59.179 [info] (platform) Ruby LSP Rails booting server
2024-11-09 07:18:04.835 [info] (platform) Finished booting Ruby LSP Rails server
2024-11-09 07:18:04.836 [info] (platform) [dry-types] Dry::Types::Type#safe is deprecated and will be removed in the next major version

2024-11-09 07:18:04.836 [info] (platform) Please use Dry::Types::Type#lax instead.

2024-11-09 07:18:04.836 [info] (platform) /home/alexander/Toptal/platform/config/application.rb:12:in `<main>'

2024-11-09 07:18:04.836 [info] (platform) your 131072x1 screen size is bogus. expect trouble
```

**Comment by erickguan** [comment]
Great, we can close the issue. Thanks for helping.

**Comment by AlexVPopov** [comment]
Closing as the problem is no longer reproducible in 0.3.26. Thank you, @erickguan, for helping! 🙇 🙏
